// src/app/components/header/header.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { IFiveDayWeather, ITodayWeather } from 'src/app/shared/model/app-weather.model';
import { WeatherService } from 'src/app/shared/service/weather.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  @Output() onTodayWeather = new EventEmitter<ITodayWeather>(); //Передаем в app.component
  @Output() onFiveDayWeather = new EventEmitter<IFiveDayWeather>(); //Передаем в app.component
  @Output() onError = new EventEmitter<number>(); //Передаем в app.component

  cityName: string = 'Минск';
  cityWeather!: ITodayWeather;
  fiveDayWeather!: IFiveDayWeather;

  errorStatus!: number;

  constructor(private weatherService: WeatherService) {
  }

  ngOnInit(): void {
    this.getWeather();
    this.getFiveDayWeather();
  }

  getWeather(): void {
    this.weatherService.getWeatherByCityName(this.cityName).subscribe((cityWeather: ITodayWeather) => {
      this.cityWeather = cityWeather;
      console.log(this.cityWeather)

      this.onTodayWeather.emit(this.cityWeather); //Передаем в app.component this.cityWeather
    }, (error: any) => {
      this.errorStatus = error.status;
      this.onError.emit(this.errorStatus); //Передаем в app.component this.errorStatus
    })
  }

  getFiveDayWeather(): void {
    this.weatherService.getFiveDayWeatherByCityName(this.cityName).subscribe((fiveDayWeather: IFiveDayWeather) => {
      this.fiveDayWeather = fiveDayWeather;

      this.onFiveDayWeather.emit(this.fiveDayWeather); //Передаем в app.component this.fiveDayWeather
    })
  }

  changeCityName(value: any) {
    this.cityName = value.target.value;
  }

}

<div class="header">
  <h1 class="title">Моя погода</h1>
  <div class="search-container">
    <input class="input-search" type="search" [value]='cityName' (input)="changeCityName($event)"/>
    <button class="button-search" (click)="getWeather()"><img src="../../../assets/images/magnifying-glass-solid.svg" alt=""></button>
  </div>
</div>

// src/Components/Header/Header.tsx
import React, { ChangeEvent, useEffect, useState } from "react";
import { useActions } from "../../Hooks/useActions";
import search from "../../images/search.svg";
import { useTypedSelector } from "../../Hooks/useTypeSelector";
import classes from "./Header.module.scss";

const Header = () => {
  const [cityName, setCityName] = useState<string>("Минск");
  const getCityName = function (value: ChangeEvent<HTMLInputElement>) {
    setCityName(value.target.value);
  };

  useEffect(() => {
    getWeatherToday(cityName);
  }, []);

  const { weatherToday } = useTypedSelector((state) => state.weatherToday);

  console.log(weatherToday);

  const { getWeatherToday } = useActions();
  return (
    <div className={classes.header}>
      <h1 className={classes.title}>Моя погода</h1>
      <div className={classes.searchContainer}>
        <input
          className={classes.inputSearch}
          type="search"
          value="Минск"
          onChange={(event) => getCityName(event)}
        />
        <button
          className={classes.buttonSearch}
          onClick={() => getWeatherToday(cityName)}
        >
          <img src={search} alt="search" />
        </button>
      </div>
    </div>
  );
};

export default Header;
